id: A5A48B4AE
base_file: f207A.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:35:32.514844
  last_modified_at: 2022-05-30 18:35:32.514871
